# Handling Null Values

In [1]:
import pandas as pd

In [45]:
df = pd.read_csv('AB_NYC_2019.csv')

In [4]:
df.sample(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
8671,6660511,Highly Desired LOCATION East V. NYC,34861715,Diana,Manhattan,East Village,40.72639,-73.98875,Entire home/apt,280,2,29,2019-01-01,0.59,1,0
32949,25979705,Pre-War Elegance in Soho / West Village,8881505,Megan,Manhattan,SoHo,40.72786,-74.00500,Entire home/apt,175,5,20,2019-06-13,2.01,1,36
26076,20803220,Romantic NYC Getaway,7913159,Cait,Manhattan,Washington Heights,40.84566,-73.93998,Entire home/apt,75,3,3,2017-12-27,0.14,1,0
20948,16586785,Williamsburg Penthouse w/ Private Roof,3781090,Jamil,Brooklyn,Williamsburg,40.70724,-73.94379,Entire home/apt,100,2,36,2019-05-27,1.19,1,0
47160,35612982,Luggage drop off ONLY! Close to LGA & JFK,108512889,Syed,Queens,Sunnyside,40.73954,-73.92095,Shared room,12,1,0,NaN,NaN,1,359

In [5]:
df.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

- ### Deleting the rows with null values

In [7]:
df.shape

(48895, 16)

In [8]:
df1 = df.dropna()

In [9]:
df1.shape

(38821, 16)

In [10]:
df1.isna().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

- ### Removing the Columns having null values

In [17]:
df2 = df.copy()

In [18]:
df2.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [19]:
df2.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [20]:
df2.drop('last_review', axis = 1, inplace = True)

In [21]:
df2.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

- ### Filling the null values

In [46]:
df3 = df.copy()

In [23]:
df3.sample(6)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
24980,20013255,Lavish Private bedroom by central park,115228513,Aly,Manhattan,Upper West Side,40.80263,-73.96458,Private room,99,1,90,2019-05-30,3.80,2,331
16206,13077317,"East 29th Street, Luxury Studio in NOMAD",22541573,Ken,Manhattan,Midtown,40.74426,-73.98535,Entire home/apt,192,30,0,NaN,NaN,87,334
5023,3613161,Exquisite SoHa/Columbia area large 2 BR,11976676,David,Manhattan,Harlem,40.80465,-73.95365,Entire home/apt,139,3,24,2017-04-26,0.49,1,0
41519,32282597,"E Flatbush! Cozy, 20 min walk to Dwnstate Hosp",242296495,Angela,Brooklyn,East Flatbush,40.64941,-73.93451,Private room,33,1,14,2019-07-06,3.09,3,37
36256,28840001,Beautiful Cozy Studio Apartment,217468746,Timothy,Staten Island,Stapleton,40.62448,-74.08317,Entire home/apt,89,1,23,2019-07-05,2.43,1,0
9614,7385651,Sunny apartment in the heart of LIC,25705189,Greta,Queens,Long Island City,40.74364,-73.95392,Entire home/apt,100,5,0,NaN,NaN,1,0

- Calculating the mean for reviews_per_month

In [56]:
mean_value = round(df3['reviews_per_month'].mean(), 2)
mean_value

1.37

In [57]:
df3['reviews_per_month'].fillna(mean_value, inplace = True)

In [39]:
df3.sample(6)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1080,454334,Private spacious studio available,2257289,Toni,Manhattan,Harlem,40.81669,-73.94267,Private room,65,1,3,2014-12-31,0.03,1,0
1744,788106,Cozy West Village Apartment,3106826,Carl,Manhattan,West Village,40.73761,-74.00043,Entire home/apt,140,2,34,2018-08-31,0.43,1,159
19430,15497821,Bluebird Hell's Kitchen 2-BR + Killer City Views,95459395,Bluebird,Manhattan,Hell's Kitchen,40.76045,-73.99929,Entire home/apt,748,30,1,2018-06-17,0.08,18,365
39817,30950765,great Location with a fireplace balcony &rooftop,16105313,Debra,Manhattan,Midtown,40.74484,-73.98355,Entire home/apt,150,20,0,NaN,1.37,2,157
14743,11654372,Amazing Combo Bedroom/Living Space,6001746,Kevin,Brooklyn,Bushwick,40.70478,-73.92767,Private room,60,21,0,NaN,1.37,1,0
3613,2159898,East Village Studio,11021180,Sheila,Manhattan,East Village,40.72671,-73.98437,Entire home/apt,190,4,216,2019-07-06,3.34,1,55

- Calculating the mode for last_review

In [52]:
mode_value = df3['last_review'].mode()[0]
mode_value

'2019-06-23'

In [53]:
df3['last_review'].fillna(mode_value, inplace = True)

In [58]:
df3.sample(6)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
5218,3769257,Spacious Stylish Sunny Retreat,19315796,Andrew,Manhattan,Midtown,40.75911,-73.96299,Private room,70,1,0,2019-06-23,1.37,1,0
41108,31968550,Brooklyn Place,196935380,Prosper,Brooklyn,Flatbush,40.63886,-73.95228,Private room,80,2,0,2019-06-23,1.37,1,88
19869,15927523,Newly renovated ground floor apt in Williamsburg,103349564,Jennifer,Brooklyn,Williamsburg,40.71463,-73.96474,Entire home/apt,250,2,53,2019-07-06,1.68,1,2
36577,29081010,金色上房,190324721,Jun Jun,Queens,Flushing,40.75914,-73.83352,Private room,70,1,5,2019-06-04,0.82,4,5
18314,14366918,Private BR in Beautiful Renovated East Village...,21882649,Joshua,Manhattan,East Village,40.73036,-73.98633,Private room,95,30,7,2016-12-29,0.20,1,238
12630,9698613,"1 Bedroom Sublet in Astoria, NY",50084376,Asijah,Queens,Ditmars Steinway,40.77472,-73.90993,Private room,35,1,2,2016-01-05,0.05,1,0

- ### Categorical Data

In [60]:
df4 = df.copy()

In [62]:
df4.sample(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
37104,29496193,Cozy + Chic Harlem Apartment,33869262,Madeline,Manhattan,Harlem,40.82364,-73.94472,Entire home/apt,125,2,19,2019-06-30,2.35,1,37
43251,33534624,Chic Blush Shine,243489304,Jackie,Manhattan,Chinatown,40.71515,-73.99099,Private room,89,4,16,2019-07-06,5.00,2,166
48569,36316748,Modern Room in the Jungles (15 min to Downtown),31422161,Pavel,Brooklyn,Bedford-Stuyvesant,40.68983,-73.92775,Private room,75,1,0,NaN,NaN,1,76
46027,35035847,TimeSquare High-level modern apartment 1BDR!,42174219,Zack,Manhattan,Theater District,40.76113,-73.98557,Private room,180,2,1,2019-06-01,0.77,1,31
11617,9040796,Lovely Studio in Midtown,21716352,Alice,Manhattan,Kips Bay,40.74208,-73.98084,Entire home/apt,120,1,4,2016-04-01,0.10,1,0

In [64]:
df4.nunique()

id                                48895
name                              47905
host_id                           37457
host_name                         11452
neighbourhood_group                   5
neighbourhood                       221
latitude                          19048
longitude                         14718
room_type                             3
price                               674
minimum_nights                      109
number_of_reviews                   394
last_review                        1764
reviews_per_month                   937
calculated_host_listings_count       47
availability_365                    366
dtype: int64

In [74]:
most_frequent = df4['last_review'].value_counts().index[0]
most_frequent

'2019-06-23'

In [76]:
df4['last_review'].fillna(most_frequent, inplace = True)

In [77]:
df4.sample(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
24168,19471352,"Dreamy Bushwick Art Apt, 15min from City, Roof...",136607675,Samantha,Brooklyn,Bedford-Stuyvesant,40.69844,-73.93921,Private room,62,1,47,2019-06-29,1.92,1,21
16566,13266202,Spacious living space in Williamsburg/Bushwick,14291958,Yiming (Steven),Brooklyn,Williamsburg,40.70644,-73.93968,Private room,60,3,2,2016-10-10,0.06,1,0
24549,19743334,Gem in South Williamsburg,3363377,Eryka,Brooklyn,Williamsburg,40.70997,-73.94902,Private room,114,2,43,2019-06-11,1.82,2,114
31943,24933530,Sunny Brooklyn apt. Quick walk to Prospect Park,104051773,Sophie,Brooklyn,East Flatbush,40.65215,-73.95219,Entire home/apt,91,3,4,2019-01-02,0.30,1,12
12728,9747682,"Private, Serene, Exposed Brick Realness Browns...",4018726,Lorraine,Brooklyn,Bedford-Stuyvesant,40.69297,-73.94522,Private room,63,3,6,2019-06-30,2.77,1,60
22331,18024760,Private Room in a beautiful apartment!,96718265,Javier & Alejandra,Brooklyn,Bedford-Stuyvesant,40.69288,-73.93285,Private room,45,1,0,2019-06-23,NaN,1,7
8432,6476426,3 Bedroom Downtown NYC loft,25646971,Ella,Manhattan,Financial District,40.71095,-74.00912,Entire home/apt,400,2,8,2018-08-16,0.19,1,44
16753,13388285,"Newly renovated, sunny room with a private bath",39808438,Easton,Brooklyn,Bushwick,40.68936,-73.91600,Private room,75,3,23,2018-08-19,0.62,5,0
18712,14815997,"Bright, quiet, super comfy chic in Upper East ...",3979831,Mj,Manhattan,Upper East Side,40.77273,-73.96344,Entire home/apt,195,2,90,2019-06-26,2.59,1,134
15409,12346131,★ HEBREWS 13:2 ★,23732730,Buddy,Bronx,Pelham Gardens,40.86323,-73.84638,Entire home/apt,450,2,81,2019-07-06,2.07,4,342

- ### Advanced

In [78]:
data = pd.read_csv('AB_NYC_2019.csv')

In [80]:
data.sample(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
30732,23773431,Comfortable home in the heart of it all,22288459,Alexi,Brooklyn,Bedford-Stuyvesant,40.69389,-73.93472,Private room,45,1,5,2019-03-24,0.33,2,0
4922,3529888,Architect's Oasis,9952523,Fabi,Brooklyn,Crown Heights,40.66919,-73.95079,Entire home/apt,125,3,10,2017-03-10,0.22,1,0
20831,16498335,Spacious private room Uptown NYC,17713747,Polly,Manhattan,Washington Heights,40.85365,-73.93298,Private room,60,15,1,2017-03-03,0.03,3,159
46928,35492112,"Spacious Bushwick 3BR, 2.5 Bath (Steps to Subw...",266531875,Willy,Brooklyn,Bushwick,40.69403,-73.91991,Entire home/apt,475,2,3,2019-07-01,3.00,3,343
19812,15860528,Big Apple Experience,102799406,Gail,Queens,Maspeth,40.71402,-73.90853,Entire home/apt,159,5,25,2019-06-21,0.97,2,299

In [85]:
data['reviews_per_month'].interpolate(inplace = True)

In [90]:
data['reviews_per_month'] = data['reviews_per_month'].round(2)

In [91]:
data.sample(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
12094,9395128,"LGA/TimeSqaure/Private BDroom+Bath, Queens",36577517,Nan,Queens,Elmhurst,40.74449,-73.88096,Private room,49,2,21,2019-06-15,0.48,2,311
28585,22148416,The Skyline Loft — Incredible Views Near 2 Trains,14364462,Ashley,Brooklyn,Bushwick,40.70597,-73.92091,Entire home/apt,127,3,9,2019-04-24,0.49,2,34
32133,25113126,Panda Pod,6801469,Kelly,Queens,College Point,40.78824,-73.84056,Entire home/apt,65,3,28,2019-06-25,2.13,1,26
47240,35650326,안전하고 조용한 숙소,40971988,Hyunje,Manhattan,Upper East Side,40.76954,-73.94959,Private room,75,1,4,2019-07-01,4.00,1,9
41898,32567344,"Bright and lovely flat in Williamsburg, Brooklyn",39329872,Maxime,Brooklyn,Williamsburg,40.70857,-73.95258,Entire home/apt,110,6,3,2019-06-21,0.98,1,25
31618,24632516,Quiet Sunlit Bedroom w/ Private Bath in Brooklyn,79322329,Elissa,Brooklyn,Bushwick,40.70133,-73.92074,Private room,115,3,45,2019-07-04,3.14,1,75
8043,6198343,Calm airy top floor W'burgh 1.5 bed,1245722,Jen,Brooklyn,Williamsburg,40.71776,-73.94538,Entire home/apt,200,3,30,2019-07-01,0.65,1,364
48297,36182819,Luxurious Studio One Stop To Manhattan!,247335568,Evelyn,Queens,Long Island City,40.74717,-73.94254,Entire home/apt,200,1,0,NaN,1.33,7,5
39720,30912652,Gorgeous Flat with Priv Patio Steps from 42nd/...,17139611,Nina,Manhattan,Hell's Kitchen,40.75718,-73.99807,Entire home/apt,375,3,1,2019-01-01,0.16,1,0
35652,28309473,Your Cozy Room,213781715,Anting,Brooklyn,Greenpoint,40.73286,-73.95086,Private room,99,1,5,2019-04-21,0.51,33,365