In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('AB_NYC_2019.csv')

In [3]:
df.sample(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
21747,17480547,Room in Brooklyn With Central Air and Heat,83351115,Samuel,Brooklyn,Bushwick,40.69484,-73.92499,Private room,50,12,0,NaN,NaN,1,0
45202,34598389,"3Bdrm home w/Parking! 10min Manhattan,5min Air...",261028352,Young,Queens,Woodside,40.74268,-73.90022,Entire home/apt,146,2,7,2019-06-30,5.00,2,89
43380,33618854,Private House in Trendy Crown Heights,253354074,Yehudis,Brooklyn,East Flatbush,40.66247,-73.93784,Entire home/apt,425,2,2,2019-06-27,2.00,2,59
900,327521,"Lovely studio in East Village, NY",82896,Esther,Manhattan,East Village,40.72500,-73.98851,Entire home/apt,150,5,1,2015-11-16,0.02,1,0
9624,7395202,Big room in Clinton Hil near subway,23425862,Gagandeep,Brooklyn,Bedford-Stuyvesant,40.69172,-73.95862,Private room,90,1,0,NaN,NaN,2,0

- ## Data Analysis for Categorical Data

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [5]:
df['id'] = df['id'].astype(str)
df['host_id'] = df['host_id'].astype(str)

In [14]:
df['neighbourhood_group'].value_counts().reset_index().rename(columns = {'neighbourhood' : 'area', 'count' : 'number_of_hotels'})

  neighbourhood_group  number_of_hotels
0           Manhattan             21661
1            Brooklyn             20104
2              Queens              5666
3               Bronx              1091
4       Staten Island               373

`showing percentage`

In [12]:
df['neighbourhood_group'].value_counts(normalize = True).reset_index().rename(columns = {'neighbourhood' : 'area'})

  neighbourhood_group  proportion
0           Manhattan    0.443011
1            Brooklyn    0.411167
2              Queens    0.115881
3               Bronx    0.022313
4       Staten Island    0.007629

In [9]:
df['neighbourhood'].value_counts()

neighbourhood
Williamsburg          3920
Bedford-Stuyvesant    3714
Harlem                2658
Bushwick              2465
Upper West Side       1971
                      ...
Fort Wadsworth           1
Richmondtown             1
New Dorp                 1
Rossville                1
Willowbrook              1
Name: count, Length: 221, dtype: int64

In [11]:
df['neighbourhood'].value_counts().reset_index().rename(columns = {'count' : 'number_of_hotels'})

          neighbourhood  number_of_hotels
0          Williamsburg              3920
1    Bedford-Stuyvesant              3714
2                Harlem              2658
3              Bushwick              2465
4       Upper West Side              1971
..                  ...               ...
216      Fort Wadsworth                 1
217        Richmondtown                 1
218            New Dorp                 1
219           Rossville                 1
220         Willowbrook                 1

[221 rows x 2 columns]

In [15]:
df_2 = df['neighbourhood'].value_counts().reset_index().rename(columns = {'count' : 'number_of_hotels'})

In [16]:
df_2[df_2['number_of_hotels'] > 1000]

         neighbourhood  number_of_hotels
0         Williamsburg              3920
1   Bedford-Stuyvesant              3714
2               Harlem              2658
3             Bushwick              2465
4      Upper West Side              1971
5       Hell's Kitchen              1958
6         East Village              1853
7      Upper East Side              1798
8        Crown Heights              1564
9              Midtown              1545
10         East Harlem              1117
11          Greenpoint              1115
12             Chelsea              1113

In [17]:
df['room_type'].value_counts()

room_type
Entire home/apt    25409
Private room       22326
Shared room         1160
Name: count, dtype: int64

In [18]:
df['room_type'].value_counts().reset_index()

         room_type  count
0  Entire home/apt  25409
1     Private room  22326
2      Shared room   1160

In [19]:
df['room_type'].value_counts(normalize = True).reset_index()

         room_type  proportion
0  Entire home/apt    0.519665
1     Private room    0.456611
2      Shared room    0.023724

- ## Data Analysis on Numerical Data

In [23]:
df['minimum_nights'].value_counts().reset_index().rename(columns = {'count' : 'number_of_hotels'})

     minimum_nights  number_of_hotels
0                 1             12720
1                 2             11696
2                 3              7999
3                30              3760
4                 4              3303
..              ...               ...
104             186                 1
105             366                 1
106              68                 1
107              87                 1
108              36                 1

[109 rows x 2 columns]

In [22]:
df['latitude'] = df['latitude'].astype(str)
df['longitude'] = df['longitude'].astype(str)
df.describe()

,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [24]:
df['price'].value_counts().reset_index().rename(columns = {'count' : 'number_of_hotels'})

     price  number_of_hotels
0      100              2051
1      150              2047
2       50              1534
3       60              1458
4      200              1401
..     ...               ...
669    780                 1
670    386                 1
671    888                 1
672    483                 1
673    338                 1

[674 rows x 2 columns]

In [25]:
df_3 = df['price'].value_counts().reset_index().rename(columns = {'count' : 'number_of_hotels'})

In [27]:
df_3[df_3['price'] > 5000]

     price  number_of_hotels
407  10000                 3
420   6500                 3
432   9999                 3
441   7500                 2
480   6000                 2
522   5250                 1
557   6800                 1
563   8000                 1
573   5100                 1
657   7703                 1
659   6419                 1
662   8500                 1