# Sampling

In [11]:
import numpy as np
import seaborn as sns

In [12]:
mpg = sns.load_dataset('mpg')

- ## Random Sampling

In [15]:
random_sample = mpg.sample(10)
random_sample

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
172,25.0,4,90.0,71.0,2223,16.5,75,europe,volkswagen dasher
356,32.4,4,108.0,75.0,2350,16.8,81,japan,toyota corolla
217,30.0,4,111.0,80.0,2155,14.8,77,usa,buick opel isuzu deluxe
266,30.0,4,98.0,68.0,2155,16.5,78,usa,chevrolet chevette
256,20.5,6,225.0,100.0,3430,17.2,78,usa,plymouth volare
60,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
241,22.0,6,146.0,97.0,2815,14.5,77,japan,datsun 810
199,20.0,6,225.0,100.0,3651,17.7,76,usa,dodge aspen se
161,16.0,6,250.0,105.0,3897,18.5,75,usa,chevroelt chevelle malibu
37,18.0,6,232.0,100.0,3288,15.5,71,usa,amc matador

- ## Systematic Sampling

In [19]:
systematic_sample = mpg.iloc[np.arange(0, len(mpg), step = 20)]
systematic_sample

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
20,25.0,4,110.0,87.0,2672,17.5,70,europe,peugeot 504
40,14.0,8,351.0,153.0,4154,13.5,71,usa,ford galaxie 500
60,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
80,22.0,4,122.0,86.0,2395,16.0,72,usa,ford pinto (sw)
100,18.0,6,250.0,88.0,3021,16.5,73,usa,ford maverick
120,19.0,4,121.0,112.0,2868,15.5,73,europe,volvo 144ea
140,14.0,8,304.0,150.0,4257,15.5,74,usa,amc matador (sw)
160,17.0,6,231.0,110.0,3907,21.0,75,usa,buick century
180,25.0,4,121.0,115.0,2671,13.5,75,europe,saab 99le
200,18.0,6,250.0,78.0,3574,21.0,76,usa,ford granada ghia
220,33.5,4,85.0,70.0,1945,16.8,77,japan,datsun f-10 hatchback
240,30.5,4,97.0,78.0,2190,14.1,77,europe,volkswagen dasher
260,18.6,6,225.0,110.0,3620,18.7,78,usa,dodge aspen
280,21.5,6,231.0,115.0,3245,15.4,79,usa,pontiac lemans v6
300,23.9,8,260.0,90.0,3420,22.2,79,usa,oldsmobile cutlass salon brougham
320,37.0,4,119.0,92.0,2434,15.0,80,japan,datsun 510 hatchback
340,25.8,4,156.0,92.0,2620,14.4,81,usa,dodge aries wagon (sw)
360,30.7,6,145.0,76.0,3160,19.6,81,europe,volvo diesel
380,36.0,4,120.0,88.0,2160,14.5,82,japan,nissan stanza xe

- ## Stratified Sampling

`Dispropotional`

In [20]:
mpg['origin'].unique()

array(['usa', 'japan', 'europe'], dtype=object)

In [24]:
mpg.groupby('origin' , group_keys = False ).apply(lambda x : x.sample(3))

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
59,23.0,4,97.0,54.0,2254,23.5,72,europe,volkswagen type 3
51,30.0,4,79.0,70.0,2074,19.5,71,europe,peugeot 304
77,22.0,4,121.0,76.0,2511,18.0,72,europe,volkswagen 411 (sw)
270,21.1,4,134.0,95.0,2515,14.8,78,japan,toyota celica gt liftback
357,32.9,4,119.0,100.0,2615,14.8,81,japan,datsun 200sx
273,23.9,4,119.0,97.0,2405,14.9,78,japan,datsun 200-sx
200,18.0,6,250.0,78.0,3574,21.0,76,usa,ford granada ghia
95,12.0,8,455.0,225.0,4951,11.0,73,usa,buick electra 225 custom
86,14.0,8,304.0,150.0,3672,11.5,73,usa,amc matador

`propostional`

In [28]:
mpg.groupby('origin' , group_keys = False ).apply(lambda x : x.sample(frac = 0.1))

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
59,23.0,4,97.0,54.0,2254,23.5,72,europe,volkswagen type 3
21,24.0,4,107.0,90.0,2430,14.5,70,europe,audi 100 ls
327,36.4,5,121.0,67.0,2950,19.9,80,europe,audi 5000s (diesel)
276,21.6,4,121.0,115.0,2795,15.7,78,europe,saab 99gle
293,31.9,4,89.0,71.0,1925,14.0,79,europe,vw rabbit custom
52,30.0,4,88.0,76.0,2065,14.5,71,europe,fiat 124b
244,43.1,4,90.0,48.0,1985,21.5,78,europe,volkswagen rabbit custom diesel
144,31.0,4,76.0,52.0,1649,16.5,74,japan,toyota corona
173,24.0,4,119.0,97.0,2545,17.0,75,japan,datsun 710
205,28.0,4,97.0,75.0,2155,16.4,76,japan,toyota corolla
149,24.0,4,120.0,97.0,2489,15.0,74,japan,honda civic
321,32.2,4,108.0,75.0,2265,15.2,80,japan,toyota corolla
348,37.7,4,89.0,62.0,2050,17.3,81,japan,toyota tercel
361,25.4,6,168.0,116.0,2900,12.6,81,japan,toyota cressida
322,46.6,4,86.0,65.0,2110,17.9,80,japan,mazda glc
35,17.0,6,250.0,100.0,3329,15.5,71,usa,chevrolet chevelle malibu
73,13.0,8,307.0,130.0,4098,14.0,72,usa,chevrolet chevelle concours (sw)
392,27.0,4,151.0,90.0,2950,17.3,82,usa,chevrolet camaro
137,13.0,8,350.0,150.0,4699,14.5,74,usa,buick century luxus (sw)
298,23.0,8,350.0,125.0,3900,17.4,79,usa,cadillac eldorado
90,12.0,8,429.0,198.0,4952,11.5,73,usa,mercury marquis brougham
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10
215,13.0,8,318.0,150.0,3755,14.0,76,usa,dodge d100
188,16.0,8,318.0,150.0,4190,13.0,76,usa,dodge coronet brougham
16,18.0,6,199.0,97.0,2774,15.5,70,usa,amc hornet
154,15.0,6,250.0,72.0,3432,21.0,75,usa,mercury monarch
222,17.0,8,260.0,110.0,4060,19.0,77,usa,oldsmobile cutlass supreme
168,23.0,4,140.0,83.0,2639,17.0,75,usa,ford pinto
48,18.0,6,250.0,88.0,3139,14.5,71,usa,ford mustang
344,39.0,4,86.0,64.0,1875,16.4,81,usa,plymouth champ
280,21.5,6,231.0,115.0,3245,15.4,79,usa,pontiac lemans v6
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
99,18.0,6,232.0,100.0,2945,16.0,73,usa,amc hornet
307,26.8,6,173.0,115.0,2700,12.9,79,usa,oldsmobile omega brougham
75,14.0,8,318.0,150.0,4077,14.0,72,usa,plymouth satellite custom (sw)
103,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
366,17.6,6,225.0,85.0,3465,16.6,81,usa,chrysler lebaron salon
80,22.0,4,122.0,86.0,2395,16.0,72,usa,ford pinto (sw)
213,13.0,8,350.0,145.0,4055,12.0,76,usa,chevy c10
259,20.8,6,200.0,85.0,3070,16.7,78,usa,mercury zephyr

# Confidence Interval

In [1]:
import numpy as np
import scipy.stats as st

`Calculating the confidence interval for 0.90, T Distribution confidence for a sample data of length 20`

In [2]:
np.random.seed(1)
data = np.random.randint(1,5, 20)

In [3]:
data

array([2, 4, 1, 1, 4, 2, 4, 2, 4, 1, 1, 2, 1, 4, 2, 1, 3, 2, 3, 1])

In [7]:
st.t.interval(0.90, len(data) - 1, np.mean(data), st.sem(data))

(1.7827298404375287, 2.717270159562471)

`Calculating the confidence interval for Z distribution for confidence level 0.90 and random data sample of length 100`

In [8]:
data2 = np.random.randint(1,20,100)

In [9]:
data2

array([ 6, 19, 12, 11, 15, 19,  5, 10, 18,  1, 14, 10, 10,  8,  2,  1, 18,
        9, 14, 16, 11,  9,  8,  4,  7, 18,  4,  5, 18, 12, 13, 17, 14, 10,
       19, 16,  1,  5, 16,  3,  8,  9, 10,  4,  8,  5,  6,  7,  9,  1,  3,
       11, 16, 16,  8, 11, 15,  1,  2, 18, 14,  4,  1, 14,  7,  7,  3, 13,
       12,  8, 14,  9, 12, 13, 12,  5,  8,  8, 14,  5, 17, 19,  1, 14, 11,
       18,  8, 11,  1, 13,  2, 10, 19,  2,  3, 13,  8,  3, 11,  1])

In [10]:
st.norm.interval(0.90, np.mean(data2), st.sem(data))

(9.195504926168, 10.084495073832)

# Hypothesis Testing

- ## Ztest

In [2]:
import numpy as np
import scipy.stats as st

In [1]:
alpha = 0.05
n = 50
sample_mean = 110
pop_mean = 100
pop_sd = 15

In [3]:
def ztest(n, sample_mean, pop_mean, pop_sd, alternate):
    z = (sample_mean - pop_mean)/(pop_sd/n**0.5)
    p_value = st.norm.sf(z)
    print(f'z-value : {z} \np-value : {p_value}')

    if(alternate == 'one-sided'):
        if(p_value < alpha):
            print('Reject the Null Hypothesis')
        else:
            print('Failed to reject the Null Hypothesis')
    elif(alternate == 'two-sided'):
        if z < alpha/2 :
            print('Reject the Null Hypothesis')
        else:
            print('Failed to reject the Null Hypothesis')

In [4]:
ztest(n, sample_mean, pop_mean, pop_sd, 'one-sided')

z-value : 4.714045207910317
p-value : 1.2142337364879197e-06
Reject the Null Hypothesis

In [5]:
# example 2 for ztest
alpha = 0.05
n = 81
sample_mean = 90
pop_mean = 82
pop_sd = 20

In [6]:
ztest(n, sample_mean, pop_mean, pop_sd, 'one-sided')

z-value : 3.5999999999999996
p-value : 0.00015910859015753396
Reject the Null Hypothesis

- ## Ttest

In [34]:
# data 
sample_mean = 140
pop_sd = 20
alpha = 0.05
data = pop_sd* np.random.randn(30) + sample_mean
print(np.mean(data), np.std(data))

143.07993623498638 22.868531899543175

In [36]:
t_statistic, p_value = st.ttest_1samp(a = data, popmean= 100)

In [37]:
print(f't_statistic : {t_statistic}\np_value : {p_value}')

t_statistic : 10.144619581411845
p_value : 4.7601972585451583e-11

In [39]:
if(p_value < alpha):
    print('Reject the Null Hypothesis')
else: 
    print('Failed to reject the Null Hypothesis')

Reject the Null Hypothesis

- ## Chi-Squared Test

In [41]:
from scipy.stats import chisquare

`The chisquare() function from the scipy.stats library helps to calculate the p_value and chi-squared value for the catogorical data and compare the expected and observed results`

The example used here has values 48,24,24 are the observed values of the subjects being favorable independent or unbiased, and the expected values are taken to be 32,32,32, Now on applying the chisquare function

- - ### Example 1

In [43]:
chi_value, p_value = chisquare([48,24,24])

In [44]:
print(f'chi-value : {chi_value}\np-value : {p_value}')

chi-value : 12.0
p-value : 0.002478752176666357

`Now this value can be compared with the alpha which is given to be equals to 0.05`

In [45]:
if p_value < alpha :
    print('Dependent (Reject H0)')
else: 
    print('Independent and (H0 holds true)')

Dependent (Reject H0)

`This implies that Reject the Null Hypothesis`

 - - ### Example 2

`In this example we test the bolts manufactuered from 5 machines and the results of defective bolts are 5,9,13,7,6 and expected are 8,8,8,8,8`

In [47]:
chi_value, p_value = chisquare([5,9,13,7,6])

In [48]:
print(f'chi-value : {chi_value}\np-value : {p_value}')
if p_value < alpha :
    print('Dependent (Reject H0)')
else: 
    print('Independent and (H0 holds true)')

chi-value : 5.0
p-value : 0.2872974951836458
Independent and (H0 holds true)

- ## Chi-Squared Test for feature extraction

In [49]:
from scipy.stats import chi2_contingency

`This function helps to compare two or more categories and tell the model which one is the more dominating and has to be extracted or removed from the dataset`

In [52]:
outlook_data = [[2,3],[4,0],[3,2]]
wind_data = [[3,3],[6,2]]

`here the outlook and wind data are no of yes and no for tennis played or not`

In [53]:
chi2_contingency(outlook_data)

Chi2ContingencyResult(statistic=3.546666666666666, pvalue=0.16976615743981124, dof=2, expected_freq=array([[3.21428571, 1.78571429],
       [2.57142857, 1.42857143],
       [3.21428571, 1.78571429]]))

In [54]:
chi2_contingency(wind_data)

Chi2ContingencyResult(statistic=0.16203703703703703, pvalue=0.687287949348002, dof=1, expected_freq=array([[3.85714286, 2.14285714],
       [5.14285714, 2.85714286]]))

In [59]:
expected_freq = [3.85714286, 2.14285714,5.14285714, 2.85714286]
wind_data = [3,3,6,2]

In [60]:
chisquare(wind_data, expected_freq)

Power_divergenceResult(statistic=0.9333333396938274, pvalue=0.8173771570701455)

`Here the chi2_contingency has a different documentation for a 2x2 matrix so, we extracted the expected_freq array and calculated the chi value for the wind data accordingly and then compare the categroies and remove accordingly`

- ## Anova

Anova helps in finding out if there is significant diffrence bw the mean of three or more groups.
Anova is of three types:
    1 Way Anova
    2 Way Anova
    MANOVA

1 Way Anova : Used to test the difference bw three or more sample groups, to test the effect of one independent variable
2 Way Anova : Used to test the effect of two independent variables 
MANOVA      : To test the effects of one independent variable on two or more dependent variables

- - ### 1 Way Anova

- - - #### Example 1

Null Hypothesis : At Least one of them is different

In [61]:
from scipy.stats import f_oneway

In [62]:
english = [2,4,2]
maths = [2,3,4]
science = [1,2,5]

In [64]:
alpha = 0.05

In [69]:
stat, p_value = f_oneway(english, maths , science)

In [70]:
print(f'Stat : {stat}\np-value : {p_value}')

Stat : 0.04999999999999999
p-value : 0.9516215013591449

In [71]:
if p_value < alpha :
    print('Reject the Null Hypothesis: At least one of them is different')
else:
   print('Failed to Reject Null Hypothesis: There is no difference')

Failed to Reject Null Hypothesis: There is no difference

- - - #### Example 2

`This is the data of different engines when different types of oil were applied`

In [72]:
performance1 = [89,89,88,78,79]
performance2 = [93,92,94,89,88]
performance3 = [89,88,89,93,90]
performance4 = [81,78,81,92,82]

In [73]:
stat, p_value = f_oneway(performance1, performance2, performance3, performance4)

In [74]:
print(f'Stat : {stat}\np-value : {p_value}')

Stat : 4.625000000000002
p-value : 0.016336459839780215

In [75]:
if p_value < alpha :
    print('Reject the Null Hypothesis: At least one of them is different')
else:
   print('Failed to Reject Null Hypothesis: There is no difference')

Reject the Null Hypothesis: At least one of them is different

- - ### 2 Way Anova

In [77]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [82]:
data_frame = pd.DataFrame({
    'Fertilizer': np.repeat(['daily', 'weekly'], 15),
    'Watering' : np.repeat(['daily', 'weekly'], 15),
    'Height' : [14,16,15,15,16,13,12,11,14,15,16,16,17,18,14,13,14,14,14,15,16,16,17,18,14,13,14,14,14,15]
})

We have three Null Hypothesis:
    1. Fertilizer does not affect the height of plants
    2. Watering does not affect the height of plants
    3. Both have no effect

In [83]:
data_frame

   Fertilizer Watering  Height
0       daily    daily      14
1       daily    daily      16
2       daily    daily      15
3       daily    daily      15
4       daily    daily      16
5       daily    daily      13
6       daily    daily      12
7       daily    daily      11
8       daily    daily      14
9       daily    daily      15
10      daily    daily      16
11      daily    daily      16
12      daily    daily      17
13      daily    daily      18
14      daily    daily      14
15     weekly   weekly      13
16     weekly   weekly      14
17     weekly   weekly      14
18     weekly   weekly      14
19     weekly   weekly      15
20     weekly   weekly      16
21     weekly   weekly      16
22     weekly   weekly      17
23     weekly   weekly      18
24     weekly   weekly      14
25     weekly   weekly      13
26     weekly   weekly      14
27     weekly   weekly      14
28     weekly   weekly      14
29     weekly   weekly      15

In [88]:
model = ols("Height~ Fertilizer + Watering + Fertilizer:Watering", data_frame).fit()

In [89]:
result = sm.stats.anova_lm(model, type = 2)

In [91]:
result

                       df     sum_sq   mean_sq         F    PR(>F)
Fertilizer            1.0   0.033333  0.033333  0.012069  0.913305
Watering              1.0   1.027463  1.027463  0.372012  0.546828
Fertilizer:Watering   1.0   0.577010  0.577010  0.208918  0.651144
Residual             28.0  77.333333  2.761905       NaN       NaN

In [ ]:
|